### ISSUE TITLE
Issue 5 for preprocessing and data transformation milestone

### ISSUE THREAD

**Issue by Rehema21** [Rehema21/Patient-Monitoring#5]
- [ ] Confirmation of the process of missing values
- [ ]  Data imputation(if applicable)
- [ ]  Data transformation ( if applicable)
