### ISSUE TITLE
Issue 6 for milestone 3: Training the model

### ISSUE THREAD

**Issue by Rehema21** [Rehema21/Patient-Monitoring#6]
- [ ] Data splitting
- [ ]  Bootstrapping
- [ ]  Cross validation (basic, repeated or LOOCV)
- [ ]  Model training for either classification, regression, association,  or clustering(if applicable)
- [ ]  Model performace comparison using resamples.(for classification and regression)
